import SwiftUI

/// First-run screen: paste the mcs_ API key generated by the Windows app
/// (Settings › Cloud Sync › API Keys). The key is verified against
/// /api/whoami before it's stored in the Keychain.
struct SignInView: View {
    @EnvironmentObject private var session: StashSession
    @State private var key = ""
    @State private var busy = false
    @State private var errorMessage: String?

    var body: some View {
        VStack(spacing: 16) {
            Image(systemName: "shippingbox")
                .font(.system(size: 56))
                .foregroundStyle(.tint)

            Text("My Crafty Stash")
                .font(.largeTitle.bold())

            Text("Paste an API key from the Windows app\n(Settings › Cloud Sync › API Keys) to browse your stash.")
                .multilineTextAlignment(.center)
                .foregroundStyle(.secondary)

            SecureField("mcs_…", text: $key)
                .textFieldStyle(.roundedBorder)
                .frame(maxWidth: 360)

            if let errorMessage {
                Text(errorMessage)
                    .font(.callout)
                    .foregroundStyle(.red)
                    .frame(maxWidth: 360)
            }

            Button {
                Task { await connect() }
            } label: {
                if busy {
                    ProgressView()
                } else {
                    Text("Connect")
                }
            }
            .buttonStyle(.borderedProminent)
            .disabled(busy || key.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
        }
        .padding(40)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    private func connect() async {
        busy = true
        defer { busy = false }
        errorMessage = nil
        do {
            try await session.signIn(apiKey: key)
        } catch {
            errorMessage = error.localizedDescription
        }
    }
}
